name: myday_tracker
description: "전 연령 대상 생활 기록 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  sqflite: ^2.3.3+2
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.3
  path_provider: ^2.1.4
  file_picker: ^8.1.6
  csv: ^6.0.0
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true